### ISSUE TITLE
test-jacobians is not passing

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-constraints#51]
Hi,

When trying to run tests, I have this error:
```
test 4
      Start  4: test-jacobians

4: Test command: /local/users/gsaurel/humanoid-path-planner/hpp-constraints/build/tests/test-jacobians
4: Test timeout computed to be: 9.99988e+06
4: Running 4 test cases...
4: /local/users/gsaurel/humanoid-path-planner/hpp-constraints/tests/test-jacobians.cc(236): error in "jacobian": Jacobian of Configuration seems wrong (central). DOF 21 at row 0: 2.7798 > 0.00012207
4: /local/users/gsaurel/humanoid-path-planner/hpp-constraints/tests/test-jacobians.cc(236): error in "jacobian": Jacobian of Configuration seems wrong (central). DOF 26 at row 0: 3.35197 > 0.00012207
4: /local/users/gsaurel/humanoid-path-planner/hpp-constraints/tests/test-jacobians.cc(236): error in "jacobian": Jacobian of Configuration seems wrong (central). DOF 24 at row 0: 2.94695 > 0.00012207
4: /local/users/gsaurel/humanoid-path-planner/hpp-constraints/tests/test-jacobians.cc(236): error in "jacobian": Jacobian of Configuration seems wrong (central). DOF 24 at row 0: 3.2716 > 0.00012207
4: /local/users/gsaurel/humanoid-path-planner/hpp-constraints/tests/test-jacobians.cc(236): error in "jacobian": Jacobian of Configuration seems wrong (central). DOF 24 at row 0: 3.47788 > 0.00012207
4: 
4: *** 5 failures detected in test suite "hpp_constraints"
 4/10 Test  #4: test-jacobians ...................***Failed    0.18 sec

```

**Comment by jmirabel** [comment]
This test passes on my computer... I have no clue about what's going on.

**Comment by nim65s** [comment]
Thanks for your answer, I will try a few things

**Comment by nim65s** [comment]
The bug disappeared when I compiled hpp-pinocchio from the latest release tarball instead of using robotpkg's binary version. 

It appeared again when I applied [a robotpkg's patch](https://github.com/nim65s/robotpkg/blob/master/math/hpp-pinocchio/patches/patch-aa) that was meant to allow compilation on 14.04.

I will ask Anthony to remove this patch.

**Comment by jmirabel** [comment]
I understand what happened but I am surprised you did not get an assert. Are you in debug mode ?

To be compliant with old version of Eigen, we should do something like this for all changes in the patch:
```c++
if (LgT::NV==Eigen::Dynamic) {
  Jq_.middleRows (row_, lg.nv()).applyOnTheLeft (JqInt)
} else {
  Jq_.middleRows<LgT::NV> (row_).applyOnTheLeft (JqInt)
}
```

**Comment by jmirabel** [comment]
humanoid-path-planner/hpp-pinocchio@749a76a should fix the problem.

**Comment by jmirabel** [comment]
But I cannot easily test it with Eigen 3.2.0.

**Comment by nim65s** [comment]
Thanks a lot, I will try it

**Comment by nim65s** [comment]
This doesn't work, as the operands of the ternary operator must have the same type, and here we have a fixed and a dynamic type: 

```
hpp-pinocchio/src/../src/jdifference-visitor.hh:47:42: error: no match for ternary 'operator?:' (operand types are 'bool', 'Eigen::DenseBase<Eigen::Ref<const Eigen::Matrix<double, -1, 1> > >::SegmentReturnType {aka Eigen::VectorBlock<Eigen::Ref<const Eigen::Matrix<double, -1, 1> >, -1>}', and 'Eigen::DenseBase<Eigen::Ref<const Eigen::Matrix<double, -1, 1> > >::FixedSegmentReturnType<7>::Type {aka Eigen::VectorBlock<Eigen::Ref<const Eigen::Matrix<double, -1, 1> >, 7>}')
_BLOCK_ACCESSOR_EIGEN(q0_,segment,LgT::NQ, iq_, lg.nq()),
```

I tried a few things without success

**Comment by nim65s** [comment]
for more readability, the types are:
```
Eigen::DenseBase<Eigen::Ref<const Eigen::Matrix<double, -1, 1> > >::SegmentReturnType                                   Eigen::DenseBase<Eigen::Ref<const Eigen::Matrix<double, -1, 1> > >::FixedSegmentReturnType<7>::Type                     
```

**Comment by jmirabel** [comment]
I forgot about that. I fixed it.

**Comment by nim65s** [comment]
Could you push your fix in the topic/eigen32 branch ?

**Comment by jmirabel** [comment]
done.

**Comment by nim65s** [comment]
no more luck:
```
[…]
hpp-pinocchio/src/../src/dintegrate-visitor.hh:35:11:   required from 'void hpp::pinocchio::liegroupType::dIntegrateVisitor_dq::operator()(const LgT&) [with LgT = se3::SpecialEuclideanOperation<3>]'
[…]
/opt/openrobots/include/pinocchio/spatial/explog.hpp:309:5: error: 'THIS_METHOD_IS_ONLY_FOR_VECTORS_OF_A_SPECIFIC_SIZE' is not a member of 'Eigen::internal::static_assertion<false>'
EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(Vector6Like,6);
```

**Comment by jmirabel** [comment]
@jcarpent That is a bug in Pinocchio. The problem is that explog does not accept dynamic size vector.

**Comment by jmirabel** [comment]
https://github.com/jmirabel/pinocchio/commit/2d8882ccf907f275b67d76454f4c852b25f8a698 should fix the issue.

**Comment by nim65s** [comment]
So there was 2 typos, fixed in https://github.com/nim65s/pinocchio/commit/400deb5258c02e4546af03646d02e833ea3d7690

After that, here is what I get in 14.04:
```
[ 25%] Building CXX object src/CMakeFiles/hpp-constraints.dir/configuration-constraint.cc.o
cd /root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/src && /usr/bin/ccache  /usr/bin/g++  -Dhpp_constraints_EXPORTS -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion    -O3 -DNDEBUG -fPIC -I/root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0 -I/root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/include -isystem /usr/include/eigen3 -isystem /opt/openrobots/include -isystem /usr/include/assimp    -DURDFDOM_COLLISION_WITH_GROUP_NAME -DWITH_URDFDOM -DWITH_HPP_FCL -DFCL_USE_ASSIMP_UNIFIED_HEADER_NAMES -DFCL_HAVE_OCTOMAP= -o CMakeFiles/hpp-constraints.dir/configuration-constraint.cc.o -c /root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/src/configuration-constraint.cc
/root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/src/configuration-constraint.cc: In member function 'virtual void hpp::constraints::ConfigurationConstraint::impl_jacobian(hpp::constraints::matrixOut_t, hpp::constraints::ConfigurationIn_t) const':
/root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/src/configuration-constraint.cc:86:93: error: no matching function for call to 'hpp::pinocchio::LiegroupSpace::Jdifference(hpp::constraints::ConfigurationIn_t&, const Eigen::Matrix<double, -1, 1>&, Eigen::Transpose<Eigen::Matrix<double, -1, 1> >, hpp::constraints::matrix_t&)'
goal_.space()->Jdifference<false> (argument, goal_.vector(), diff_.transpose(), unused);
^
/root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/src/configuration-constraint.cc:86:93: note: candidate is:
In file included from /opt/openrobots/include/hpp/pinocchio/liegroup-element.hh:20:0,
from /root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/include/hpp/constraints/differentiable-function.hh:24,
from /root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/include/hpp/constraints/configuration-constraint.hh:25,
from /root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/src/configuration-constraint.cc:17:
make[2]: Leaving directory `/root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0'
/opt/openrobots/include/hpp/pinocchio/liegroup-space.hh:217:12: note: template<bool ApplyOnTheLeft> void hpp::pinocchio::LiegroupSpace::Jdifference(hpp::pinocchio::vectorIn_t, hpp::pinocchio::vectorIn_t, hpp::pinocchio::matrixOut_t, hpp::pinocchio::matrixOut_t) const
void Jdifference (vectorIn_t q0, vectorIn_t q1, matrixOut_t J0, matrixOut_t J1) const;
^
/opt/openrobots/include/hpp/pinocchio/liegroup-space.hh:217:12: note:   template argument deduction/substitution failed:
make[1]: Leaving directory `/root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0'
/root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/src/configuration-constraint.cc:86:93: note:   cannot convert '((Eigen::DenseBase<Eigen::Matrix<double, -1, 1> >*)(&((const hpp::constraints::ConfigurationConstraint*)this)->hpp::constraints::ConfigurationConstraint::diff_))->Eigen::DenseBase<Derived>::transpose<Eigen::Matrix<double, -1, 1> >()' (type 'Eigen::Transpose<Eigen::Matrix<double, -1, 1> >') to type 'hpp::pinocchio::matrixOut_t {aka Eigen::Ref<Eigen::Matrix<double, -1, -1> >}'
goal_.space()->Jdifference<false> (argument, goal_.vector(), diff_.transpose(), unused);
^
```

**Comment by jmirabel** [comment]
Thanks for the feedback. I forced push the fix on hpp-constraints branch topic/eigen32.

**Comment by nim65s** [comment]
I had this error:

```
 /root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/src/configuration-constraint.cc: In member function 'virtual void hpp::constraints::ConfigurationConstraint::impl_jacobian(hpp::constraints::matrixOut_t, hpp::constraints::ConfigurationIn_t) const':
/root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/src/configuration-constraint.cc:86:78: error: no matching function for call to 'hpp::pinocchio::LiegroupSpace::Jdifference(hpp::constraints::ConfigurationIn_t&, const Eigen::Matrix<double, -1, 1>&, Eigen::Matrix<double, 1, -1>&, hpp::constraints::matrix_t&)'
goal_.space()->Jdifference<false> (argument, goal_.vector(), J_, unused);
^
/root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/src/configuration-constraint.cc:86:78: note: candidate is:
In file included from /opt/openrobots/include/hpp/pinocchio/liegroup-element.hh:20:0,
from /root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/include/hpp/constraints/differentiable-function.hh:24,
from /root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/include/hpp/constraints/configuration-constraint.hh:25,
from /root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/src/configuration-constraint.cc:17:
/opt/openrobots/include/hpp/pinocchio/liegroup-space.hh:217:12: note: template<bool ApplyOnTheLeft> void hpp::pinocchio::LiegroupSpace::Jdifference(hpp::pinocchio::vectorIn_t, hpp::pinocchio::vectorIn_t, hpp::pinocchio::matrixOut_t, hpp::pinocchio::matrixOut_t) const
void Jdifference (vectorIn_t q0, vectorIn_t q1, matrixOut_t J0, matrixOut_t J1) const;
^
/opt/openrobots/include/hpp/pinocchio/liegroup-space.hh:217:12: note:   template argument deduction/substitution failed:
/root/robotpkg/path/hpp-constraints/work.6ab9f1384d29/hpp-constraints-4.2.0/src/configuration-constraint.cc:86:78: note:   cannot convert '((const hpp::constraints::ConfigurationConstraint*)this)->hpp::constraints::ConfigurationConstraint::J_' (type 'Eigen::Matrix<double, 1, -1>') to type 'hpp::pinocchio::matrixOut_t {aka Eigen::Ref<Eigen::Matrix<double, -1, -1> >}'
goal_.space()->Jdifference<false> (argument, goal_.vector(), J_, unused);
^
```

So I changed your `mutable Eigen::Matrix<value_type, 1, Eigen::Dynamic> J_;` by a `mutable Eigen::Matrix<value_type, Eigen::Dynamic, Eigen::Dynamic> J_;`

And now I have a bunch of:
```
hpp-constraints/src/static-stability.cc:173:35: error: 'class Eigen::JacobiSVD<Eigen::Matrix<double, -1, -1>, 2>' has no member named 'rank'
```

It turns out that [the rank() method has not been added in Eigen before 3.2.2](https://github.com/eigenteam/eigen-git-mirror/commit/35212455d7911f6bdb47a63416c6148b642abe35)

**Comment by jmirabel** [comment]
It's gonna be tedious to be compatible with Eigen 3.2.0. In 14.04 previously, we installed a more recent version of Eigen.

Let's not put HPP in robotpkg for Ubuntu 14.04 (or at least keep this for later). I think @florent-lamiraux will agree.

**Comment by nim65s** [comment]
I agree.

I will just cc @pFernbach here, because I think that he needs to get a few thing work with the current HPP in 14.04 before beeing able to upgrade to 16.04. 
Anyway, in his case, installing a more recent version of Eigen in 14.04 might help.

Still, should we still open PRs for: 
- https://github.com/humanoid-path-planner/hpp-pinocchio/compare/devel...topic/eigen32
- https://github.com/stack-of-tasks/pinocchio/compare/devel...nim65s:matrix_size (after a merge of https://github.com/stack-of-tasks/pinocchio/pull/561)
- https://github.com/humanoid-path-planner/hpp-constraints/commit/f99ef04e85ed8dbfebe46cbbfb0199acb262ac8d with `Eigen::Dynamic` (this one I am less sure…)

**Comment by pFernbach** [comment]
We changed our mind and I will stop trying to use the current devel/master on 14.04.
We are also going to switch rbprm to 16.

**Comment by jmirabel** [comment]
For the one in pinocchio, yes, we can open a PR.
I'll deal with the two others.

**Comment by jmirabel** [comment]
Is this still ongoing ?
